/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_RegistroUsuarios;
import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.MetodosUsuarios;

/**
 *
 * @author Lanfor
 */
public class FRM_RegistroUsuarios extends javax.swing.JFrame {

    
    public Controlador_FRM_RegistroUsuarios controlador_FRM_RegistroUsuarios;
    MetodosUsuarios metodosUsuarios;
    public FRM_RegistroUsuarios(MetodosUsuarios metodosUsuarios, FRM_VentanaPrincipal frm_VentanaPrincipal) {
        initComponents();
        setSize(375, 265);
        setLocation(350, 200);
        setResizable(false);
        controlador_FRM_RegistroUsuarios=new Controlador_FRM_RegistroUsuarios(metodosUsuarios, this, frm_VentanaPrincipal);
        this.metodosUsuarios=metodosUsuarios;
        btn_Registrar.addActionListener(controlador_FRM_RegistroUsuarios);
        
    }
    
    public String[] devolverInformacion()
    {
        String[] arreglo={jt_NombUsuario.getText(),jt_Correo.getText(),jp_Contrasena.getText(),jcb_TipoUsuario.getItemAt(jcb_TipoUsuario.getSelectedIndex())};
        return arreglo;
    }
    public int mostrarMensajeOpcional(String msj)
    {
        return JOptionPane.showConfirmDialog(this, msj);
    }
    public void mostrarMensaje(String msj)
    {
         JOptionPane.showMessageDialog(this, msj);
    }
    public void usuarioRojo()
    {
        jt_NombUsuario.setForeground(Color.RED);
    }
    public void usuarioNegro()
    {
        jt_NombUsuario.setForeground(Color.BLACK);
    }
    public void resetearVentana()
    {
        jt_NombUsuario.setText("");
        jt_Correo.setText("");
        jp_Contrasena.setText("");
        jcb_TipoUsuario.setSelectedIndex(0);
    }
    
    public String getCorreo()
    {
        return jt_Correo.getText();
    }
    
    public String getContrasena()
    {
        return jp_Contrasena.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_NombUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jl_Contrasena = new javax.swing.JLabel();
        jt_NombUsuario = new javax.swing.JTextField();
        jt_Correo = new javax.swing.JTextField();
        btn_Registrar = new javax.swing.JButton();
        jp_Contrasena = new javax.swing.JPasswordField();
        jcb_TipoUsuario = new javax.swing.JComboBox<>();
        jl_TipoUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Registro de Usuarios");
        setBackground(new java.awt.Color(51, 102, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(null);

        jl_NombUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jl_NombUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jl_NombUsuario.setText("Nomb.Usuario:");
        getContentPane().add(jl_NombUsuario);
        jl_NombUsuario.setBounds(60, 30, 90, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Correo:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 70, 41, 14);

        jl_Contrasena.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jl_Contrasena.setForeground(new java.awt.Color(255, 255, 255));
        jl_Contrasena.setText("Contraseña:");
        getContentPane().add(jl_Contrasena);
        jl_Contrasena.setBounds(60, 110, 68, 14);
        getContentPane().add(jt_NombUsuario);
        jt_NombUsuario.setBounds(150, 30, 150, 30);
        getContentPane().add(jt_Correo);
        jt_Correo.setBounds(150, 70, 150, 30);

        btn_Registrar.setBackground(new java.awt.Color(255, 255, 0));
        btn_Registrar.setText("Registrar");
        getContentPane().add(btn_Registrar);
        btn_Registrar.setBounds(160, 180, 110, 23);
        getContentPane().add(jp_Contrasena);
        jp_Contrasena.setBounds(150, 110, 150, 30);

        jcb_TipoUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jcb_TipoUsuario.setMaximumRowCount(5);
        jcb_TipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Desarrollador", "Administrador", "Usuario" }));
        getContentPane().add(jcb_TipoUsuario);
        jcb_TipoUsuario.setBounds(150, 150, 150, 20);

        jl_TipoUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jl_TipoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jl_TipoUsuario.setText("Tipo.Usuario:");
        getContentPane().add(jl_TipoUsuario);
        jl_TipoUsuario.setBounds(60, 140, 80, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoMiPaguinaWeb.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 370, 230);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
       System.out.println("Salio ventana Usuario");
       if(controlador_FRM_RegistroUsuarios.controlador_FRM_VentanaPrincipal.getTipoAlmacenamiento().equalsIgnoreCase("Archivo Plano"))
       {
           metodosUsuarios.escribirSobreArchivo();
       }
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jcb_TipoUsuario;
    private javax.swing.JLabel jl_Contrasena;
    private javax.swing.JLabel jl_NombUsuario;
    private javax.swing.JLabel jl_TipoUsuario;
    private javax.swing.JPasswordField jp_Contrasena;
    private javax.swing.JTextField jt_Correo;
    private javax.swing.JTextField jt_NombUsuario;
    // End of variables declaration//GEN-END:variables
}
