package vista;

import controlador.Controlador_FRM_TipoAlmacenamiento;
import controlador.Controlador_FRM_VentanaPrincipal;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Lanfor
 */
public class FRM_TipoAlmacenamiento extends javax.swing.JFrame {

    /**
     * Creates new form FRM_TipoAlmacenamiento
     */
    Controlador_FRM_TipoAlmacenamiento controlador_FRM_TipoAlmacenamiento;
    public FRM_TipoAlmacenamiento(Controlador_FRM_VentanaPrincipal controlador_FRM_VentanaPrincipal)
    {
        initComponents();
        setSize(650, 250);
        setLocation(400, 150);
        show();
        controlador_FRM_TipoAlmacenamiento=new Controlador_FRM_TipoAlmacenamiento(this, controlador_FRM_VentanaPrincipal);
        agregarEventos();
    }
    
    public void agregarEventos()
    {
        btn_Aceptar.addActionListener(controlador_FRM_TipoAlmacenamiento);
        btn_Cancelar.addActionListener(controlador_FRM_TipoAlmacenamiento);
    }
    public boolean selecionArchivoPlano()
    {
        return jrb_ArchivoPlano.isSelected();
    }
    public boolean selecionArchivoXML()
    {
        return jrb_ArchivoXML.isSelected();
    }
    public boolean selecionBD()
    {
        return jrb_BD.isSelected();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng_TipoAlmacenamiento = new javax.swing.ButtonGroup();
        jrb_ArchivoPlano = new javax.swing.JRadioButton();
        jrb_ArchivoXML = new javax.swing.JRadioButton();
        jrb_BD = new javax.swing.JRadioButton();
        jl_Ask = new javax.swing.JLabel();
        btn_Aceptar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        getContentPane().setLayout(null);

        btng_TipoAlmacenamiento.add(jrb_ArchivoPlano);
        jrb_ArchivoPlano.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrb_ArchivoPlano.setForeground(new java.awt.Color(204, 204, 204));
        jrb_ArchivoPlano.setSelected(true);
        jrb_ArchivoPlano.setText("Archivos Planos");
        jrb_ArchivoPlano.setBorderPainted(true);
        getContentPane().add(jrb_ArchivoPlano);
        jrb_ArchivoPlano.setBounds(210, 100, 130, 23);

        btng_TipoAlmacenamiento.add(jrb_ArchivoXML);
        jrb_ArchivoXML.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrb_ArchivoXML.setForeground(new java.awt.Color(204, 204, 204));
        jrb_ArchivoXML.setText("Archivos XML");
        jrb_ArchivoXML.setBorderPainted(true);
        getContentPane().add(jrb_ArchivoXML);
        jrb_ArchivoXML.setBounds(350, 100, 110, 23);

        btng_TipoAlmacenamiento.add(jrb_BD);
        jrb_BD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrb_BD.setForeground(new java.awt.Color(204, 204, 204));
        jrb_BD.setText("Base de datos");
        jrb_BD.setBorderPainted(true);
        getContentPane().add(jrb_BD);
        jrb_BD.setBounds(470, 100, 120, 23);

        jl_Ask.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jl_Ask.setForeground(new java.awt.Color(255, 255, 255));
        jl_Ask.setText("Elija con cúal tipo de Almacenamiento desea trabajar");
        jl_Ask.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jl_Ask);
        jl_Ask.setBounds(140, 10, 490, 26);

        btn_Aceptar.setBackground(new java.awt.Color(51, 51, 255));
        btn_Aceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/check_sign_icon_blue.png"))); // NOI18N
        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btn_Aceptar);
        btn_Aceptar.setBounds(270, 150, 120, 30);

        btn_Cancelar.setBackground(new java.awt.Color(255, 0, 0));
        btn_Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btn_Cancelar);
        btn_Cancelar.setBounds(410, 150, 120, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/benderBinario.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 650, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.ButtonGroup btng_TipoAlmacenamiento;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jl_Ask;
    private javax.swing.JRadioButton jrb_ArchivoPlano;
    private javax.swing.JRadioButton jrb_ArchivoXML;
    private javax.swing.JRadioButton jrb_BD;
    // End of variables declaration//GEN-END:variables
}
