/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_MantenimientoCursos;

/**
 *
 * @author administrador
 */
public class Panel_Cursos extends javax.swing.JPanel 
{

    /**
     * Creates new form Panel_Cursos
     */
    Controlador_FRM_MantenimientoCursos controlador;
    public Panel_Cursos() 
    {
        initComponents();
        cargarCreditos();
        deshabilitarCampos();
        
    }
    
    public void cargarCreditos()
    {
        this.jcb_Creditos.removeAllItems();
        for(int i=0; i<=10; i++)
        {
            this.jcb_Creditos.addItem(""+i);
        }
        this.jcb_Creditos.setSelectedIndex(4);//que aparezca en el comboBox selecionado el 4
    }

    
    public void agregarEventos(Controlador_FRM_MantenimientoCursos controlador)
    {
        this.btn_ConsultaRapida.addActionListener(controlador);
        this.controlador=controlador;
    }
    
    public String devolverSigla()
    {
        return this.jt_Siglas.getText();
    }
    
    public void habilitarEdicion()
    {
        this.jt_Siglas.setEnabled(false);
        this.jt_Nombre.setEnabled(true);
        this.jcb_Creditos.setEnabled(true);
        this.jt_Horario.setEnabled(true);
    }
    
    public void mostrarInformacion(String arreglo[])
    {
        this.jt_Nombre.setText(arreglo[0]);
        this.jcb_Creditos.setSelectedIndex(Integer.parseInt(arreglo[1]));
        this.jt_Horario.setText(arreglo[2]);
    }
    
    public void habilitarCampos()
    {
        this.jt_Nombre.setEnabled(true);
        this.jcb_Creditos.setEnabled(true);
        this.jt_Horario.setEnabled(true);
    }
    
    public String[] devolverInformacion()
    {
        String informacion[]=new String[4];
        informacion[0]=this.jt_Siglas.getText();
        informacion[1]=this.jt_Nombre.getText();
        informacion[2]=""+this.jcb_Creditos.getSelectedIndex();
        informacion[3]=this.jt_Horario.getText();
        
        return informacion;
    }
    
    public void deshabilitarCampos()
    {
        this.jt_Siglas.setEnabled(true);
        this.jt_Siglas.setText("");
        this.jt_Nombre.setEnabled(false);
        this.jt_Nombre.setText("");
        
        this.jcb_Creditos.setSelectedIndex(4);
        this.jcb_Creditos.setEnabled(false);
        
        this.jt_Horario.setEnabled(false);
        this.jt_Horario.setText("");
        
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Siglas = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Creditos = new javax.swing.JLabel();
        jt_Siglas = new javax.swing.JTextField();
        jt_Nombre = new javax.swing.JTextField();
        jcb_Creditos = new javax.swing.JComboBox();
        btn_ConsultaRapida = new javax.swing.JButton();
        jl_Horario = new javax.swing.JLabel();
        jt_Horario = new javax.swing.JTextField();

        jl_Siglas.setText("Siglas");

        jl_Nombre.setText("Nombre");

        jl_Creditos.setText("Creditos");

        jt_Siglas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jt_SiglasKeyPressed(evt);
            }
        });

        jcb_Creditos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_ConsultaRapida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        btn_ConsultaRapida.setActionCommand("ConsultaRapida");

        jl_Horario.setText("Horario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_Creditos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_Creditos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Nombre)
                            .addComponent(jl_Siglas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jt_Siglas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ConsultaRapida))
                            .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_Horario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jt_Horario)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Siglas)
                            .addComponent(jt_Siglas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btn_ConsultaRapida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre)
                    .addComponent(jt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_Creditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Creditos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Horario)
                    .addComponent(jt_Horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_SiglasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_SiglasKeyPressed
        if(evt.getKeyCode()==10)
        this.controlador.buscar();
    }//GEN-LAST:event_jt_SiglasKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ConsultaRapida;
    private javax.swing.JComboBox jcb_Creditos;
    private javax.swing.JLabel jl_Creditos;
    private javax.swing.JLabel jl_Horario;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Siglas;
    private javax.swing.JTextField jt_Horario;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_Siglas;
    // End of variables declaration//GEN-END:variables
}
